### ISSUE TITLE
not working with serotonin

### ISSUE THREAD

**Issue by kewla1d** [PoomSmart/EmojiFontManager#12]
it worked in settings and other bootstrapped apps, but not unbootstrapped ones. please fix this. iOS 16.5 iPhone12, if it matters.

**Comment by PoomSmart** [comment]
I suggest checking with Serotonin developers first. There should be zero actions required for regular tweaks to work on a semi but "jailbreak". If you believe the solution is to change this tweak somehow, then you may create a new issue.

Also I don't own any Serotonin-compatible devices.
