### ISSUE TITLE
TTC - Older iOS 

### ISSUE THREAD

**Issue by vXBaKeRXv** [PoomSmart/EmojiFontManager#2]
Do you think you could get the TTC to run on 9.x and lower with EFM ?

Possible Route:
Hook the 'Apple Color Emoji' FontFamily name inside the TTC..
TTF ( "Apple Color Emoji")  + TTF (".Apple Color Emoji UI") = TTC

This would help with package doubling on the emoji fonts repo and simpler for users.

**Comment by PoomSmart** [comment]
TTC unknowingly supports iOS < 10 according to testing. Version 0.0.5c has been released.
