### ISSUE TITLE
Error loading preference bundle iOS 6.1.6

### ISSUE THREAD

**Issue by Jap2-0** [PoomSmart/EmojiFontManager#4]
After installing EmojiFontManager (with or without the iOS 13 font), all that shows up in settings is "There was an error loading the preference bundle for EmojiFontManager."

Additionally, BytaFont crashes when trying to install the 13.2 font; the 12.1 font and other fonts work fine. (I don't know if that's an issue with BytaFont or on your end.)

Help making either way work would be greatly appreciated - if there's any way I can help, let me know.

iPod touch 4g, iOS 6.1.6, Emoji font manager 0.0.6-1

**Comment by vXBaKeRXv** [comment]
Hey sorry late response! Thanks for reporting. I will look into this some on font or if needed let poom know. Might be sometime -

🤝

**Comment by Jap2-0** [comment]
Hey @vXBaKeRXv , just thought I'd check back and see if there was an update here?

**Comment by vXBaKeRXv** [comment]
Why not on 0.0.7.1 ?

**Comment by Jap2-0** [comment]
Ah, I must've missed that update.  That fixes it, thanks!

**Comment by vXBaKeRXv** [comment]
Hahaha your welcome! I assumed you updated or avoiding it. Poom is very good at solving things 😁
