### ISSUE TITLE
Error loading preference bundle

### ISSUE THREAD

**Issue by SlightlyPeckish** [PoomSmart/EmojiFontManager#5]
iPhone XR iOS 13.5
I get this error when trying to access the preferences
![Error](https://user-images.githubusercontent.com/21175434/89957460-638d4e00-dc2f-11ea-9c9c-2efd4d2f5a42.png)

**Comment by PoomSmart** [comment]
Does it work if you update to 0.0.7.2?

**Comment by SlightlyPeckish** [comment]
> Does it work if you update to 0.0.7.2?

Just updated and I'm still getting the same error
![error](https://user-images.githubusercontent.com/21175434/90005740-8c453000-dc8f-11ea-9b97-872ffb8d2ff3.png)

**Comment by PoomSmart** [comment]
Alright, can you try to reinstall “EmojiLibrary” as well?

**Comment by SlightlyPeckish** [comment]
I just reinstalled them both at the same time but it didn't work but then after I did the exact same thing again but it's working now I don't know why I'm sorry this has been awkward but thank you for the support 👍🏻

**Comment by PoomSmart** [comment]
I guess the culprit was that both EFM and EL were not compiled properly. Glad to see it fixed.
