### ISSUE TITLE
0.0.8.2 crashes apps

### ISSUE THREAD

**Issue by HightechFairy** [PoomSmart/EmojiFontManager#6]
I'm running Odyssey on 13.5 and with the latest update Slide for Reddit and Twitter crashed for me, I didn't test any other apps since I downgraded to 0.0.8.1 and everything was back to normal again.

**Comment by PoomSmart** [comment]
Cannot help without providing crash log.

**Comment by HightechFairy** [comment]
https://drive.google.com/drive/folders/1-6QF40a5xk59MJ_K7-KEaoiTP6EXEBYU

**Comment by HightechFairy** [comment]
that link comtains fresh logs for twitter, discord and slide, hope it helps

**Comment by PoomSmart** [comment]
Can you try this test version? @HightechFairy 
[com.ps.emojifontmanager_0.0.8.3_iphoneos-arm.deb.zip](https://github.com/PoomSmart/EmojiFontManager/files/5321924/com.ps.emojifontmanager_0.0.8.3_iphoneos-arm.deb.zip)

**Comment by HightechFairy** [comment]
yes, that works just fine again, thank you very much
