### ISSUE TITLE
Error loading EFMPref.bundle

### ISSUE THREAD

**Issue by calvin079** [PoomSmart/EmojiFontManager#7]
I saw that there was a closed issue with this same exact problem and i thought i was saved, but i've tried reinstalling EFM and EmojiLibrary multiple times now (about 10 times) and nothing is working.
![IMG_1518](https://user-images.githubusercontent.com/13414122/131596310-5229a6de-22bd-4511-b831-b9a7b506878f.PNG)
![IMG_1519](https://user-images.githubusercontent.com/13414122/131596316-d6cc689c-a657-4024-a151-c091cd6df7b0.PNG)

**Comment by PoomSmart** [comment]
iOS version?

**Comment by calvin079** [comment]
THANK YOU! I can see the available fonts now!

There is one slight bug? and it's that the respring and reset emoji preferences buttons dont work. I just used a different tweak to respring and I was able to see the new emojis though.
Thanks again for the quick fix. Still can't believe how fast that was.

**Comment by Barbaransef** [comment]
Hi, I'm having the same problem. It has a fix? @PoomSmart
